### ISSUE TITLE
When no playbooks are found, differentiate between "the api server works but is empty" vs "could not connect to remote api server"

### ISSUE THREAD

**Issue by dmsimard** [ansible-community/ara-web#9]
Right now, if there's either no API server running or if there are no playbooks found, the error returned will be the same:

![Screenshot from 2019-05-28 11-46-20](https://user-images.githubusercontent.com/1291204/58492081-3cd41c00-813e-11e9-97a8-e4b4ac43230f.png)

We should be able to tell if the remote API server is up and running by retrieving the version of ARA API server at "/", for example:

![Screenshot from 2019-05-28 11-48-13](https://user-images.githubusercontent.com/1291204/58492229-7efd5d80-813e-11e9-9e62-e1ae30f782a9.png)

**Comment by guillaumevincent** [comment]
yes let me improve this

**Comment by dmsimard** [comment]
Tested https://review.opendev.org/#/c/661940/ and works for me !

When the server is offline or can't be reached:
![Screenshot from 2019-05-29 08-51-29](https://user-images.githubusercontent.com/1291204/58558584-36ea4380-81ef-11e9-852c-0d685d04c863.png)

When the server is online but empty:
![Screenshot from 2019-05-29 08-52-40](https://user-images.githubusercontent.com/1291204/58558606-44073280-81ef-11e9-8fdf-b3c227639ccc.png)

Great work, thanks @guillaumevincent !
